"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Word={id:string;word:string;meaning:string;example:string;level:string;tags:string;stage:number;due:string;pos?:string;definition?:string};
type View="today"|"library"|"stats"|"settings";
type Mistake={wordId:string;count:number;lastResult:"again"|"fuzzy";updatedAt:string};
type StudyEvent={wordId:string;result:"again"|"fuzzy"|"known";at:string};
const seed:Word[]=[
 {id:"1",word:"abandon",meaning:"放弃；抛弃",example:"Never abandon your hope.",level:"CET-4",tags:"核心",stage:0,due:""},
 {id:"2",word:"compelling",meaning:"引人入胜的；令人信服的",example:"She made a compelling argument.",level:"CET-6",tags:"高频",stage:1,due:""},
 {id:"3",word:"inevitable",meaning:"不可避免的",example:"Change is inevitable.",level:"CET-6",tags:"阅读",stage:0,due:""},
 {id:"4",word:"maintain",meaning:"维持；保养；坚称",example:"Maintain a healthy balance.",level:"CET-4",tags:"核心",stage:2,due:""},
 {id:"5",word:"perspective",meaning:"观点；视角",example:"Try to see it from another perspective.",level:"CET-4",tags:"写作",stage:0,due:""},
];
const today=()=>new Date().toISOString().slice(0,10);
const quotes=["The secret of getting ahead is getting started.","Success is the sum of small efforts, repeated day in and day out.","Great things are done by a series of small things brought together.","It always seems impossible until it's done.","Dream big. Start small. Act now."];
const wordMeta:Record<string,{pos:string;definition:string}>={abandon:{pos:"v. [T]",definition:"to leave someone or something behind, or to stop doing something before it is finished"},compelling:{pos:"adj.",definition:"very exciting and interesting, or strong enough to make you believe something"},inevitable:{pos:"adj.",definition:"certain to happen and impossible to avoid or prevent"},maintain:{pos:"v. [T]",definition:"to keep something in good condition or at the same level"},perspective:{pos:"n. [C]",definition:"a particular way of considering or understanding something"}};

export default function Home(){
 const [view,setView]=useState<View>("today"),[words,setWords]=useState<Word[]>(seed),[index,setIndex]=useState(0),[flipped,setFlipped]=useState(false),[reviewed,setReviewed]=useState(false),[done,setDone]=useState(0),[streak,setStreak]=useState(1),[dailyTarget,setDailyTarget]=useState(30),[mistakes,setMistakes]=useState<Mistake[]>([]),[studyEvents,setStudyEvents]=useState<StudyEvent[]>([]),[liveDefinition,setLiveDefinition]=useState(""),[definitionLoading,setDefinitionLoading]=useState(false),[libraryTab,setLibraryTab]=useState<"all"|"mistakes">("all"),[activeDeck,setActiveDeck]=useState<"core"|"mistakes">("core"),[email,setEmail]=useState(""),[loginSent,setLoginSent]=useState(false),[loginBusy,setLoginBusy]=useState(false),[showLogin,setShowLogin]=useState(false),[showImport,setShowImport]=useState(false),[paste,setPaste]=useState(""),[exam,setExam]=useState("2026-12-12"),[reminder,setReminder]=useState("20:00"),[notice,setNotice]=useState(""),[online,setOnline]=useState(true),fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const raw=localStorage.getItem("lexiloop-state");if(raw){try{const s=JSON.parse(raw);setWords(s.words||seed);setDone(s.done||0);setStreak(s.streak||1);setDailyTarget(s.dailyTarget||30);setMistakes(s.mistakes||[]);setStudyEvents(s.studyEvents||[]);setExam(s.exam||"2026-12-12");setReminder(s.reminder||"20:00")}catch{}};fetch("/cet6-core-3500.json").then(r=>r.json()).then((builtIn:Word[])=>setWords(existing=>{const custom=existing.filter(w=>!w.id.startsWith("cet6-")&&!seed.some(s=>s.id===w.id));return [...builtIn,...custom]})).catch(()=>{});setOnline(navigator.onLine);const on=()=>setOnline(navigator.onLine);addEventListener("online",on);addEventListener("offline",on);if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js");return()=>{removeEventListener("online",on);removeEventListener("offline",on)}},[]);
 useEffect(()=>{localStorage.setItem("lexiloop-state",JSON.stringify({words,done,streak,exam,reminder,dailyTarget,mistakes,studyEvents}))},[words,done,streak,exam,reminder,dailyTarget,mistakes,studyEvents]);
 const mistakeWords=mistakes.map(m=>words.find(w=>w.id===m.wordId)).filter(Boolean) as Word[],studyWords=activeDeck==="mistakes"?mistakeWords:words,current=studyWords[index%Math.max(studyWords.length,1)],days=Math.max(1,Math.ceil((new Date(exam).getTime()-Date.now())/86400000)),daily=dailyTarget,progress=Math.min(100,Math.round(done/Math.max(1,daily+3)*100)),dayIndex=Math.floor(Date.now()/86400000),wordOfDay=words.length?words[dayIndex%words.length]:seed[0],quote=quotes[dayIndex%quotes.length],currentMeta=current?wordMeta[current.word.toLowerCase()]||{pos:current.pos||"word",definition:current.definition||"English definition is not available for this imported word yet."}:{pos:"",definition:""},dailyMeta=wordMeta[wordOfDay.word.toLowerCase()]||{pos:wordOfDay.pos||"word",definition:wordOfDay.definition||""};
 const currentDefinition=currentMeta.definition.startsWith("English definition is not available")?liveDefinition||"英文释义加载中…":currentMeta.definition;
 const dateKey=(date:Date)=>date.toLocaleDateString("en-CA"),todayKey=dateKey(new Date()),todayEvents=studyEvents.filter(e=>dateKey(new Date(e.at))===todayKey),todayDone=todayEvents.length,studiedCount=new Set(studyEvents.map(e=>e.wordId)).size,weekCounts=Array.from({length:7},(_,offset)=>{const d=new Date();d.setDate(d.getDate()-(6-offset));const key=dateKey(d);return studyEvents.filter(e=>dateKey(new Date(e.at))===key).length}),activeDays=new Set(studyEvents.map(e=>dateKey(new Date(e.at))));let liveStreak=0;for(let offset=0;offset<366;offset++){const d=new Date();d.setDate(d.getDate()-offset);if(activeDays.has(dateKey(d)))liveStreak++;else if(offset>0)break}
 const review=(score:0|1|2)=>{if(!online){setNotice("当前离线，请恢复网络后再提交学习进度。");return}const delay=score===2?Math.max(2,Math.pow(2,(current?.stage||0)+1)):score===1?1:0.17;setWords(v=>v.map(w=>w.id===current.id?{...w,stage:score===0?0:w.stage+1,due:new Date(Date.now()+delay*86400000).toISOString()}:w));if(score<2)setMistakes(list=>{const old=list.find(x=>x.wordId===current.id);return old?list.map(x=>x.wordId===current.id?{...x,count:x.count+1,lastResult:score===0?"again":"fuzzy",updatedAt:new Date().toISOString()}:x):[...list,{wordId:current.id,count:1,lastResult:score===0?"again":"fuzzy",updatedAt:new Date().toISOString()}]});setStudyEvents(events=>[...events,{wordId:current.id,result:score===0?"again":score===1?"fuzzy":"known",at:new Date().toISOString()}]);setDone(v=>v+1);setFlipped(true);setReviewed(true)};
 const nextWord=()=>{setIndex(v=>(v+1)%Math.max(studyWords.length,1));setFlipped(false);setReviewed(false)};
 const parse=(text:string)=>{const rows=text.replace(/^\ufeff/,"").split(/\r?\n/).filter(Boolean);const start=/^word[,\t]/i.test(rows[0]||"")?1:0;const added:Word[]=[],bad:string[]=[];rows.slice(start).forEach((r,i)=>{const p=r.includes("\t")?r.split("\t"):r.split(",");if(!p[0]?.trim()||!p[1]?.trim())bad.push(`${i+1+start}`);else added.push({id:crypto.randomUUID(),word:p[0].trim(),meaning:p[1].trim(),example:p[2]?.trim()||"",level:p[3]?.trim()||"CET",tags:p[4]?.trim()||"",pos:p[5]?.trim()||"",definition:p[6]?.trim()||"",stage:0,due:""})});const old=new Set(words.map(w=>w.word.toLowerCase()));const unique=added.filter(w=>!old.has(w.word.toLowerCase()));setWords(v=>[...v,...unique]);setNotice(`已导入 ${unique.length} 个单词${bad.length?`，第 ${bad.join("、")} 行格式有误`:""}`);setShowImport(false);setPaste("")};
 const file=(f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>parse(String(r.result));r.readAsText(f,"utf-8")};
 const speak=()=>{if(!current||!("speechSynthesis" in window)){setNotice("当前浏览器不支持语音播放。");return}const u=new SpeechSynthesisUtterance(current.word);u.lang="en-US";u.rate=.82;speechSynthesis.cancel();speechSynthesis.speak(u)};
 useEffect(()=>{if(!current)return;const builtIn=wordMeta[current.word.toLowerCase()]?.definition||current.definition;if(builtIn){setLiveDefinition(builtIn);return}const cacheKey=`lexiloop-definition-${current.word.toLowerCase()}`,cached=localStorage.getItem(cacheKey);if(cached){setLiveDefinition(cached);return}setDefinitionLoading(true);setLiveDefinition("");fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(current.word)}`).then(r=>r.ok?r.json():Promise.reject()).then(data=>{const definition=data?.[0]?.meanings?.[0]?.definitions?.[0]?.definition||"暂未查到英文释义";setLiveDefinition(definition);localStorage.setItem(cacheKey,definition)}).catch(()=>setLiveDefinition("暂未查到英文释义，请稍后重试")).finally(()=>setDefinitionLoading(false))},[current?.word]);
 const sendLogin=async()=>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key){setNotice("真实登录尚未配置：需要先连接 Supabase 项目并填写公开连接信息。");return}setLoginBusy(true);try{const response=await fetch(`${url}/auth/v1/otp`,{method:"POST",headers:{"Content-Type":"application/json",apikey:key,Authorization:`Bearer ${key}`},body:JSON.stringify({email,options:{emailRedirectTo:location.origin}})});if(!response.ok)throw new Error((await response.json())?.msg||"邮件发送失败");setLoginSent(true);setNotice("登录邮件已真实发送，请检查收件箱。")}catch(error){setNotice(error instanceof Error?error.message:"登录邮件发送失败")}finally{setLoginBusy(false)}};
 const notify=async()=>{if(!("Notification" in window)){setNotice("当前浏览器不支持系统通知，已使用页内提醒。");return}const p=await Notification.requestPermission();if(p==="granted"){new Notification("背词时间到 📚",{body:"今天的单词很少，现在开始吧。",icon:"/icon-192.png"});setNotice("测试通知已发送，该设备已订阅。")}else setNotice("通知权限未开启，将使用页内提醒。")};
 return <main>
  {!online&&<div className="offline">离线模式 · 可继续浏览，进度提交需联网</div>}
  <aside><div className="logo"><span>L</span><b>LexiLoop</b></div><nav>{[["today","今日学习","01"],["library","我的词库","02"],["stats","学习统计","03"],["settings","提醒设置","04"]].map(x=><button key={x[0]} className={view===x[0]?"active":""} onClick={()=>setView(x[0] as View)}><i>{x[2]}</i>{x[1]}</button>)}</nav><div className="aside-note"><small>KEEP GOING</small><strong>{streak}</strong><span>连续学习天数</span></div><button className="user" onClick={()=>setShowLogin(true)}><span>HU</span><div><b>学习者</b><small>点击登录同步</small></div></button></aside>
  <section className="content"><header><div><p>DAILY WORDS, LASTING MEMORY</p><h1>{view==="today"?quote:view==="library"?"你的词汇资产。":view==="stats"?"每一次回想都算数。":"在合适的时间叫醒你。"}</h1></div><button className="avatar" onClick={()=>setShowLogin(true)}>HU</button></header>
  {view==="today"&&<><div className="dashboard"><article className="plan"><div className="eyebrow"><span>今日计划</span><b>{progress}%</b></div><h2>{daily}<small>新词</small><em>+</em>3<small>复习</small></h2><div className="bar"><i style={{width:`${progress}%`}}/></div><p>考试日期 {exam} · 距今天 {days} 天</p></article><article className="quote"><span>WORD OF THE DAY</span><strong>{wordOfDay.word}</strong><p><b>{wordOfDay.pos||"word"}</b> · {wordOfDay.meaning}</p></article></div>
  <section className="study"><div className="study-head"><div><span>FOCUS MODE · {activeDeck==="core"?"六级核心 3500":"错题本"}</span><h2>当前学习</h2></div><p>{studyWords.length?index%studyWords.length+1:0} / {studyWords.length}</p></div>{current?<><button className={`word-card ${flipped?"flip":""}`} onClick={()=>setFlipped(v=>!v)} aria-label="翻转单词卡"><div className="tag">{current.level} · {current.tags}</div><small>{flipped?"释义":"TAP TO REVEAL"}</small><strong>{flipped?current.meaning:current.word}</strong><p>{flipped?<><span className="definition">{currentDefinition}</span><span>{current.example||"暂无例句"}</span></>:"点击卡片查看释义"}</p></button>{reviewed&&<div className="answer-reveal"><b>{currentMeta.pos}</b><span>{current.meaning}</span><small className="english-definition">{currentDefinition}</small><small>{current.example}</small></div>}<div className="actions"><button onClick={()=>review(0)} disabled={reviewed}><b>不认识</b><small>10 分钟后</small></button><button onClick={()=>review(1)} disabled={reviewed}><b>有点模糊</b><small>明天</small></button><button className="know" onClick={reviewed?nextWord:()=>review(2)}><b>{reviewed?"下一个":"认识"}</b><small>{reviewed?"继续学习":"间隔复习"}</small></button></div></>:<div className="empty">词库是空的，去导入你的第一批单词吧。</div>}</section></>}
  {view==="library"&&<section className="panel"><div className="panel-head"><div><span>VOCABULARY</span><h2>{libraryTab==="all"?`六级核心词库 · 共 ${words.length} 个单词`:`错题本 · ${mistakes.length} 个待加强单词`}</h2></div><button className="primary" onClick={()=>setShowImport(true)}>+  导入词库</button></div><div className="deck-picker"><button className={activeDeck==="core"?"active core":"core"} onClick={()=>{setActiveDeck("core");setIndex(0)}}><span>01 / CET-6</span><strong>六级词汇<br/>核心 3500 词</strong><p>完整核心词库 · 按每日计划学习</p><b>{words.length} WORDS →</b></button><button className={activeDeck==="mistakes"?"active mistakes":"mistakes"} onClick={()=>{setActiveDeck("mistakes");setIndex(0)}}><span>02 / REVIEW</span><strong>我的<br/>错题本</strong><p>模糊和不认识的单词自动收录</p><b>{mistakes.length} WORDS →</b></button></div><div className="deck-toolbar"><div><b>当前学习：{activeDeck==="core"?"六级核心 3500":"错题本"}</b><span>{activeDeck==="core"?"每天按计划推进新词":"集中攻克薄弱单词"}</span></div><button className="primary" disabled={activeDeck==="mistakes"&&!mistakes.length} onClick={()=>{setIndex(0);setFlipped(false);setReviewed(false);setView("today")}}>开始学习 →</button></div><div className="library-tabs"><button className={libraryTab==="all"?"active":""} onClick={()=>setLibraryTab("all")}>全部单词 <b>{words.length}</b></button><button className={libraryTab==="mistakes"?"active":""} onClick={()=>setLibraryTab("mistakes")}>错题本 <b>{mistakes.length}</b></button></div>{libraryTab==="mistakes"&&mistakes.length===0?<div className="empty">还没有错题。学习时选择“不认识”或“有点模糊”的单词会自动出现在这里。</div>:<div className="word-list">{(libraryTab==="all"?words:mistakes.map(m=>words.find(w=>w.id===m.wordId)).filter(Boolean) as Word[]).map(w=>{const mistake=mistakes.find(m=>m.wordId===w.id);return <div key={w.id}><div><b>{w.word}</b><span>{w.meaning}</span></div><small>{mistake?`${mistake.lastResult==="again"?"不认识":"有点模糊"} · ${mistake.count} 次`:w.level+" · "+(w.tags||"未分类")}</small>{libraryTab==="mistakes"?<span className="row-actions"><button onClick={()=>{setIndex(words.findIndex(x=>x.id===w.id));setFlipped(false);setReviewed(false);setView("today")}}>去复习</button><button onClick={()=>setMistakes(v=>v.filter(x=>x.wordId!==w.id))}>移出</button></span>:<button onClick={()=>setWords(v=>v.filter(x=>x.id!==w.id))}>删除</button>}</div>})}</div>}</section>}
  {view==="stats"&&<section className="panel"><div className="panel-head"><div><span>YOUR PROGRESS</span><h2>学习全景 · 六级核心 3500</h2></div></div><div className="stat-grid"><article><strong>{todayDone}</strong><span>今日完成</span></article><article><strong>{studiedCount}</strong><span>已学单词</span></article><article><strong>{liveStreak}</strong><span>连续天数</span></article></div><div className="week"><h3>近 7 天学习</h3>{weekCounts.map((n,i)=><div key={i}><i title={`${n} 次复习`} style={{height:`${Math.max(6,Math.min(100,n/Math.max(1,...weekCounts)*100))}%`}}/><span>{["五","六","日","一","二","三","今"][i]}</span></div>)}</div></section>}
  {view==="settings"&&<section className="panel settings"><div className="panel-head"><div><span>REMINDER</span><h2>学习计划</h2></div></div><label>每日新词数<input type="number" min="1" max="300" value={dailyTarget} onChange={e=>setDailyTarget(Math.max(1,Number(e.target.value)))}/></label><label>考试日期<input type="date" value={exam} onChange={e=>setExam(e.target.value)}/></label><label>每日提醒时间<input type="time" value={reminder} onChange={e=>setReminder(e.target.value)}/></label><label>时区<input value={Intl.DateTimeFormat().resolvedOptions().timeZone} readOnly/></label>{daily>100&&<div className="warning">⚠ 按当前词量，每天需学习 {daily} 个新词，建议调整考试日期。</div>}<div className="device"><div><b>当前设备</b><small>浏览器系统通知</small></div><button className="primary" onClick={notify}>订阅并测试</button></div><p className="hint">登录并配置云端后，每台授权设备都会在 {reminder} 收到提醒。</p></section>}
  {view==="today"&&current&&<button className="floating-speaker" onClick={speak} aria-label={`播放 ${current.word} 的英文发音`}>🔊 播放当前单词发音</button>}
  </section>
  <nav className="mobile-nav">{[["today","今日"],["library","词库"],["stats","统计"],["settings","提醒"]].map(x=><button className={view===x[0]?"active":""} onClick={()=>setView(x[0] as View)} key={x[0]}>{x[1]}</button>)}</nav>
  {showImport&&<div className="modal"><div className="dialog"><button className="close" onClick={()=>setShowImport(false)}>×</button><span>IMPORT WORDS</span><h2>导入你的词库</h2><p>每行使用“单词,释义”，或上传 UTF-8 CSV。例句、等级、标签、词性和英文释义可选。</p><textarea value={paste} onChange={e=>setPaste(e.target.value)} placeholder={"resilient,有韧性的\nsubstantial,大量的"}/><div className="dialog-actions"><input ref={fileRef} hidden type="file" accept=".csv,text/csv" onChange={e=>file(e.target.files?.[0])}/><button onClick={()=>fileRef.current?.click()}>上传 CSV</button><a download="lexiloop-template.csv" href={'data:text/csv;charset=utf-8,'+encodeURIComponent('word,meaning,example,level,tags,pos,definition\nabandon,放弃,Never abandon hope.,CET-4,核心,v. [T],to leave someone or something behind')}>下载模板</a><button className="primary" onClick={()=>parse(paste)} disabled={!paste.trim()}>预览并导入</button></div></div></div>}
  {showLogin&&<div className="modal"><div className="dialog login"><button className="close" onClick={()=>setShowLogin(false)}>×</button><div className="logo"><span>L</span><b>LexiLoop</b></div><h2>{loginSent?"检查你的邮箱":"同步你的进度"}</h2>{loginSent?<p>验证邮件已发送至 <b>{email}</b>。点击邮件中的链接即可登录。</p>:<><p>使用邮箱验证码登录，在所有设备上保存词库和学习进度。</p><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/><button className="primary wide" onClick={sendLogin} disabled={!email.includes("@")||loginBusy}>{loginBusy?"正在发送…":"发送登录邮件"}</button></>}</div></div>}
  {notice&&<button className="toast" onClick={()=>setNotice("")}>{notice}<b>×</b></button>}
 </main>
}










